# Generated by Django 2.2.4 on 2019-09-26 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fruits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=100)),
                ('fruits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruits.Fruits')),
            ],
        ),
    ]
